apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: patch-http-route
  namespace: localstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-http-route
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get"]

  # Patch created resource with K8s secret
  #  k describe crd/httproutes.gateway.networking.k8s.io | grep api --context=2
  #  k api-resources | grep http


# - apiGroups: ["gateway.networking.k8s.io"]
#   resources: ["httproutes"]
#   verbs: ["get", "list", "patch"]
#   #verbs: ["*"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: patch-http-route
subjects:
- kind: ServiceAccount
  name: patch-http-route
  namespace: localstack
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: patch-http-route
  apiGroup: rbac.authorization.k8s.io